name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployemnt
        run: |
          curl --fail --show-error \
            "https://spravna.com/deploy?key=${{ secrets.DEPLOY_SECRET }}"
